dist: xenial

sudo: required

services:
  - docker

before_install:
  - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
  - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz

script:
  - make image
  - ./trivy --exit-code 0 --severity HIGH --no-progress openebs/linux-utils:ci
  - ./trivy --exit-code 1 --severity CRITICAL --no-progress openebs/linux-utils:ci

after_success:
  - make push
